version: '3'
services:
  web:
    build: .
    container_name: "inspector"
    ports:
      - "5000:5000"
  #  volumes:
  #      - .:/code      
  mongodb:
    image: mongo:latest
    container_name: "mongodb-inspector"
    ports:
      - "27017:27017"
    command: "mongod"