version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"      
  mongodb:
    image: mongo:latest
    container_name: "mongodb-inspector"
    ports:
      - "27017:27017"
    command: "mongod"